# Generated by Django 5.0.3 on 2024-04-17 23:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Flashcard', '0001_initial'),
        ('Mazos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='flashcard',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='flashcard',
            name='contenido',
        ),
        migrations.AddField(
            model_name='flashcard',
            name='frente',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='flashcard',
            name='reverso',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='flashcard',
            name='mazo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flashcards', to='Mazos.deck'),
        ),
    ]
