# Generated by Django 4.1.3 on 2024-04-22 02:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('idiomas', '0001_initial'),
        ('Accounts', '0002_useraccount_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='native_idiom',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='idiomas.idiom'),
        ),
    ]
