# Generated by Django 5.0.3 on 2024-04-12 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Documents', '0002_alter_pdfdocument_fecha_subida_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(max_length=255)),
                ('fecha_Creacion', models.DateTimeField(auto_now_add=True)),
                ('idDocumento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Documents.pdfdocument')),
            ],
        ),
    ]
