# Generated by Django 4.1.3 on 2024-04-21 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='note',
            old_name='fecha_Creacion',
            new_name='fecha_creacion',
        ),
    ]
