# Generated by Django 4.1.3 on 2024-03-30 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='fecha_subida',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pdfdocument',
            name='ultima_vez_abierto',
            field=models.DateField(blank=True, null=True),
        ),
    ]
