# Generated by Django 4.1.3 on 2024-04-19 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Documents', '0003_remove_pdfdocument_base64_pdfdocument_archivo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pdfdocument',
            name='archivo_url',
            field=models.URLField(blank=True, max_length=1024, null=True),
        ),
    ]
